name 'aggressivex-webmin'
version '0.5.1'
source 'git://github.com/aggressivex/puppet-webmin.git'
author 'Luis M. Hdez - Aggressivex NetWorks'
license 'MIT'
summary 'Webmin module'
description 'Webmin module'
project_page 'http://github.com/aggressivex/puppet-webmin'